# Generated by Django 6.0.4 on 2026-05-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productpublishlog_channel_connection'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok')], max_length=20)),
                ('account_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramConnectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField()),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_username', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='stores.connection')),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramChannelConnection',
        ),
    ]
