# Generated by Django 6.0.4 on 2026-04-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublishlog',
            name='channel_connection',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product_publish_logs', to='stores.telegramchannelconnection'),
            preserve_default=False,
        ),
    ]
