# Generated by Django 6.0.4 on 2026-04-18 21:07

import konversa.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpublishlog_channel_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=konversa.utils.upload_product_image_to),
        ),
    ]
