# Generated by Django 6.0.4 on 2026-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpublishlog',
            name='channel_connection',
        ),
    ]
