# Generated by Django 6.0.4 on 2026-05-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productpublishlog_channel_connection'),
        ('stores', '0002_alter_store_deleted_at_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublishlog',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_publish_logs', to='stores.connection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpublishlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
