# Generated by Django 6.0.4 on 2026-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productpublishlog_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpublishlog',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productpublishlog',
            name='post_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productpublishlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
